(()=>{
'use strict';
const $=id=>document.getElementById(id), clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const tools=[['pencil','✎','Lápis','Desenha pixels.','P'],['brush','●','Pincel','Pinta com tamanho variável.','B'],['eraser','⌫','Borracha','Apaga pixels.','E'],['fill','▧','Preenchimento','Preenche áreas contíguas.','G'],['picker','◉','Conta-gotas','Escolhe uma cor.','I'],['line','╱','Linha','Linha pixel a pixel.','L'],['rect','□','Retângulo','Retângulo pixelado.','R'],['circle','○','Círculo','Elipse pixelada.','C'],['select','▣','Seleção','Seleciona uma área.','S'],['move','✥','Mover','Move a seleção.','M'],['zoom','⌕','Zoom','Aproxima ou afasta.','Z']];
const palette0=['#1F2933','#4B5563','#9CA3AF','#E5E7EB','#FFFFFF','#D97757','#F2B880','#F4D06F','#6F9E75','#5B8E9B','#6B7A8F','#766B8F','#B56B86','#8B6F5A','#A7BFA1','#C7D2D9'];
const S={name:'Meu desenho',w:32,h:32,bg:'#FFFFFF',grid:true,zoom:16,tool:'pencil',size:1,color:'#6B7A8F',prev:'#FFFFFF',palette:[...palette0],recent:[],frames:[],frame:0,activeLayer:null,history:[],future:[],clipboard:null,selection:null,dark:false,playing:false,fps:12,loop:true,symmetry:false,dither:false,onion:false,paletteLimit:0,drag:null,space:false};
const canvas=$('pixelCanvas'),surface=$('canvasSurface');
const uid=()=>crypto.randomUUID?crypto.randomUUID():Math.random().toString(36).slice(2);
const blank=()=>Array(S.w*S.h).fill(null), idx=(x,y)=>y*S.w+x, inside=(x,y)=>x>=0&&y>=0&&x<S.w&&y<S.h;
function mkLayer(name,pixels){return{id:uid(),name,visible:true,locked:false,opacity:1,pixels:pixels?pixels.slice():blank()}}
function mkFrame(){return{layers:[mkLayer('Fundo'),mkLayer('Camada 1')]}}
function current(){return S.frames[S.frame]}
function active(){let f=current();return f&&f.layers.find(l=>l.id===S.activeLayer)||f?.layers.at(-1)}
function snap(){return{frames:JSON.parse(JSON.stringify(S.frames)),frame:S.frame,activeLayer:S.activeLayer,selection:S.selection&&{...S.selection}}}
function commit(){S.history.push(snap());if(S.history.length>80)S.history.shift();S.future=[]}
function restore(v){S.frames=v.frames;S.frame=clamp(v.frame,0,S.frames.length-1);S.activeLayer=v.activeLayer;S.selection=v.selection;ensureActive();render()}
function undo(){if(!S.history.length)return;S.future.push(snap());restore(S.history.pop());save();toast('Desfeito')}
function redo(){if(!S.future.length)return;S.history.push(snap());restore(S.future.pop());save();toast('Refeito')}
function save(show=false){try{const d={...S,history:[],future:[],drag:null,clipboard:null};localStorage.setItem('pixel-studio-v3',JSON.stringify(d));$('autosave').textContent='Salvo automaticamente';$('autosave').classList.add('saved');if(show)toast('Projeto salvo')}catch(e){toast('Falha ao salvar')}}
function load(){try{let d=JSON.parse(localStorage.getItem('pixel-studio-v3')||localStorage.getItem('pixel-studio-v2'));if(!d)throw 0;Object.assign(S,d);S.history=[];S.future=[];S.clipboard=null;S.drag=null;S.frames=S.frames||[];if(!S.frames.length)throw 0;ensureActive()}catch(e){S.frames=[mkFrame()];S.activeLayer=S.frames[0].layers[1].id}}
function ensureActive(){let f=current();if(!f)return;if(!f.layers.length)f.layers.push(mkLayer('Camada 1'));if(!f.layers.some(l=>l.id===S.activeLayer))S.activeLayer=f.layers.at(-1).id}
function hex(v){v=(v||'').trim();if(!v.startsWith('#'))v='#'+v;if(/^#[0-9a-f]{3}$/i.test(v))v='#'+v.slice(1).split('').map(c=>c+c).join('');return /^#[0-9a-f]{6}$/i.test(v)?v.toUpperCase():null}
function rgb(v){let h=v.slice(1),n=parseInt(h,16);return[n>>16&255,n>>8&255,n&255]}
function setColor(c){c=hex(c);if(!c)return;S.prev=S.color;S.color=c;$('colorPicker').value=c;$('hexInput').value=c;$('rgbInput').value=rgb(c).join(', ');renderPalette()}
function addRecent(c){S.recent=[c,...S.recent.filter(x=>x!==c)].slice(0,16)}
function sizePaint(l,x,y,c,size=S.size){let r=Math.floor((size-1)/2),r2=size%2?r:r+1;for(let yy=-r;yy<=r2;yy++)for(let xx=-r;xx<=r2;xx++){let X=x+xx,Y=y+yy;if(inside(X,Y))l.pixels[idx(X,Y)]=c}}
function points(x,y){let p=[[x,y]];if(S.symmetry)p.push([S.w-1-x,y],[x,S.h-1-y],[S.w-1-x,S.h-1-y]);return [...new Map(p.map(a=>[a.join(','),a])).values()]}
function paint(x,y,c=S.color){let l=active();if(!l||l.locked)return;for(const [X,Y] of points(x,y))sizePaint(l,X,Y,c)}
function line(x0,y0,x1,y1,fn){let dx=Math.abs(x1-x0),sx=x0<x1?1:-1,dy=-Math.abs(y1-y0),sy=y0<y1?1:-1,e=dx+dy;for(;;){fn(x0,y0);if(x0===x1&&y0===y1)break;let e2=2*e;if(e2>=dy){e+=dy;x0+=sx}if(e2<=dx){e+=dx;y0+=sy}}}
function shape(kind,a,b){let l=active();if(!l||l.locked)return;if(kind==='line'){line(a.x,a.y,b.x,b.y,(x,y)=>paint(x,y));return}let x0=Math.min(a.x,b.x),x1=Math.max(a.x,b.x),y0=Math.min(a.y,b.y),y1=Math.max(a.y,b.y),cx=(x0+x1)/2,cy=(y0+y1)/2,rx=Math.max(.5,(x1-x0)/2),ry=Math.max(.5,(y1-y0)/2);for(let y=y0;y<=y1;y++)for(let x=x0;x<=x1;x++){let dx=(x-cx)/rx,dy=(y-cy)/ry,q=dx*dx+dy*dy,ok=kind==='rect'?(x===x0||x===x1||y===y0||y===y1):(q<=1.15&&q>=.55);if(ok)paint(x,y)}}
function flood(x,y){let l=active();if(!l||l.locked)return;let old=l.pixels[idx(x,y)];if(old===S.color)return;let q=[[x,y]],seen=new Uint8Array(S.w*S.h);while(q.length){let[a,b]=q.pop();if(!inside(a,b))continue;let i=idx(a,b);if(seen[i]||l.pixels[i]!==old)continue;seen[i]=1;l.pixels[i]=S.color;q.push([a+1,b],[a-1,b],[a,b+1],[a,b-1])}}
function point(e){let r=canvas.getBoundingClientRect();return{x:Math.floor((e.clientX-r.left)*S.w/r.width),y:Math.floor((e.clientY-r.top)*S.h/r.height)}}
function validPoint(p){return p&&inside(p.x,p.y)}
function selectionData(){let s=S.selection,l=active();if(!s||!l)return null;let p=[];for(let y=0;y<s.h;y++)for(let x=0;x<s.w;x++)p.push(l.pixels[idx(s.x+x,s.y+y)]);return{s:{...s},pixels:p}}
function clearSel(){let d=selectionData();if(!d)return;commit();let l=active();for(let y=0;y<d.s.h;y++)for(let x=0;x<d.s.w;x++)l.pixels[idx(d.s.x+x,d.s.y+y)]=null;render();save()}
function copy(cut=false){let d=selectionData();if(!d){toast('Selecione uma área primeiro');return}S.clipboard=d;if(cut)clearSel();else toast('Copiado')}
function paste(){let d=S.clipboard;if(!d){toast('Nada para colar');return}let l=active();if(!l||l.locked)return;commit();let s=S.selection||{x:0,y:0,w:d.s.w,h:d.s.h},ox=clamp(s.x,0,S.w-d.s.w),oy=clamp(s.y,0,S.h-d.s.h);for(let y=0;y<d.s.h;y++)for(let x=0;x<d.s.w;x++){let v=d.pixels[y*d.s.w+x];if(v)l.pixels[idx(ox+x,oy+y)]=v}S.selection={x:ox,y:oy,w:d.s.w,h:d.s.h};render();save()}
function moveSel(dx,dy){let d=selectionData(),l=active();if(!d||!l||l.locked)return;let nx=clamp(d.s.x+dx,0,S.w-d.s.w),ny=clamp(d.s.y+dy,0,S.h-d.s.h);if(nx===d.s.x&&ny===d.s.y)return;commit();for(let y=0;y<d.s.h;y++)for(let x=0;x<d.s.w;x++)l.pixels[idx(d.s.x+x,d.s.y+y)]=null;for(let y=0;y<d.s.h;y++)for(let x=0;x<d.s.w;x++)l.pixels[idx(nx+x,ny+y)]=d.pixels[y*d.s.w+x];S.selection={x:nx,y:ny,w:d.s.w,h:d.s.h};render();save()}
function drawScene(ctx,frame,includeBg=true,opacity=1){if(includeBg){ctx.fillStyle=S.bg;ctx.fillRect(0,0,S.w,S.h)}for(const l of frame.layers){if(!l.visible)continue;ctx.globalAlpha=l.opacity*opacity;for(let y=0;y<S.h;y++)for(let x=0;x<S.w;x++){let v=l.pixels[idx(x,y)];if(v){ctx.fillStyle=v;ctx.fillRect(x,y,1,1)}}}ctx.globalAlpha=1}
function renderCanvas(){canvas.width=S.w;canvas.height=S.h;canvas.style.width=Math.max(1,S.w*S.zoom)+'px';canvas.style.height=Math.max(1,S.h*S.zoom)+'px';let c=canvas.getContext('2d');c.imageSmoothingEnabled=false;c.clearRect(0,0,S.w,S.h);drawScene(c,current());if(S.onion&&S.frames.length>1){let prev=S.frames[S.frame-1];if(prev){c.save();c.globalAlpha=.22;for(const l of prev.layers){for(let i=0;i<l.pixels.length;i++){let v=l.pixels[i];if(v){let x=i%S.w,y=Math.floor(i/S.w);c.fillStyle=v;c.fillRect(x,y,1,1)}}}c.restore()}}if(S.grid&&S.zoom>=3){c.beginPath();c.strokeStyle=S.dark?'rgba(255,255,255,.14)':'rgba(30,40,50,.13)';c.lineWidth=.05;for(let x=0;x<=S.w;x++){c.moveTo(x,0);c.lineTo(x,S.h)}for(let y=0;y<=S.h;y++){c.moveTo(0,y);c.lineTo(S.w,y)}c.stroke()}renderSelection()}
function renderSelection(){let b=$('selectionBox'),s=S.selection;if(!s){b.style.display='none';return}let r=canvas.getBoundingClientRect(),sr=surface.getBoundingClientRect();b.style.display='block';b.style.left=r.left-sr.left+s.x*r.width/S.w+'px';b.style.top=r.top-sr.top+s.y*r.height/S.h+'px';b.style.width=s.w*r.width/S.w+'px';b.style.height=s.h*r.height/S.h+'px'}
function thumb(frame,w=42,h=42){let c=document.createElement('canvas');c.width=S.w;c.height=S.h;c.style.width=w+'px';c.style.height=h+'px';let x=c.getContext('2d');x.imageSmoothingEnabled=false;drawScene(x,frame);return c}
function renderLayers(){let e=$('layers');e.innerHTML='';[...current().layers].reverse().forEach(l=>{let row=document.createElement('div');row.className='layer '+(l.id===S.activeLayer?'selected ':'')+(l.locked?'locked':'');row.draggable=true;row.dataset.id=l.id;let t=thumb({layers:[l]});t.className='layer-thumb';let n=document.createElement('span');n.className='layer-name';n.textContent=l.name;n.title=l.name;let v=document.createElement('button');v.className='icon-btn';v.textContent=l.visible?'◉':'○';v.title=l.visible?'Ocultar':'Mostrar';let k=document.createElement('button');k.className='icon-btn';k.textContent=l.locked?'▣':'□';k.title=l.locked?'Desbloquear':'Bloquear';row.append(t,n,v,k);row.onclick=ev=>{if(ev.target===v||ev.target===k)return;S.activeLayer=l.id;renderLayers();renderCanvas()};v.onclick=()=>{l.visible=!l.visible;render();save()};k.onclick=()=>{l.locked=!l.locked;render();save()};row.ondragstart=e=>{e.dataTransfer.setData('text/plain',l.id)};row.ondragover=e=>e.preventDefault();row.ondrop=e=>{e.preventDefault();reorderLayer(e.dataTransfer.getData('text/plain'),l.id)};e.append(row)})}
function reorderLayer(a,b){let ls=current().layers,ia=ls.findIndex(l=>l.id===a),ib=ls.findIndex(l=>l.id===b);if(ia<0||ib<0||ia===ib)return;commit();let [x]=ls.splice(ia,1);ls.splice(ib,0,x);render();save()}
function renderPalette(){let draw=(id,a)=>{let e=$(id);e.innerHTML='';a.forEach(c=>{let b=document.createElement('button');b.className='swatch '+(c===S.color?'active':'');b.style.background=c;b.title=c;b.onclick=()=>setColor(c);e.append(b)})};draw('palette',S.palette);draw('recentColors',S.recent)}
function renderFrames(){let e=$('frames');e.innerHTML='';S.frames.forEach((f,i)=>{let r=document.createElement('div');r.className='frame '+(i===S.frame?'selected':'');r.draggable=true;r.dataset.i=i;r.append(Object.assign(document.createElement('span'),{className:'frame-number',textContent:i+1}),thumb(f));r.onclick=()=>selectFrame(i);r.ondragstart=ev=>ev.dataTransfer.setData('text/plain',String(i));r.ondragover=ev=>ev.preventDefault();r.ondrop=ev=>{ev.preventDefault();reorderFrame(+ev.dataTransfer.getData('text/plain'),i)};if(S.frames.length>1){let d=document.createElement('button');d.className='frame-remove';d.textContent='×';d.title='Excluir frame';d.onclick=ev=>{ev.stopPropagation();deleteFrame(i)};r.append(d)}e.append(r)});$('frameInfo').textContent=`Frame ${S.frame+1} de ${S.frames.length}`}
function reorderFrame(a,b){if(a===b||a<0||b<0||a>=S.frames.length||b>=S.frames.length)return;commit();let [f]=S.frames.splice(a,1);S.frames.splice(b,0,f);S.frame=b;ensureActive();render();save()}
function selectFrame(i){S.frame=clamp(i,0,S.frames.length-1);S.selection=null;ensureActive();render()}
function addFrame(dup=true){commit();let src=current(),f=dup?JSON.parse(JSON.stringify(src)):mkFrame();S.frames.splice(S.frame+1,0,f);S.frame++;S.activeLayer=f.layers.at(-1).id;S.selection=null;render();save()}
function deleteFrame(i=S.frame){if(S.frames.length<=1){toast('O projeto precisa de pelo menos um frame');return}commit();S.frames.splice(i,1);S.frame=clamp(S.frame,0,S.frames.length-1);ensureActive();render();save()}
function shiftFrame(d){reorderFrame(S.frame,S.frame+d)}
function play(){S.playing=!S.playing;$('playBtn').textContent=S.playing?'❚❚ Pausar':'▶ Reproduzir';if(S.playing)tick()}
let timer=0;function tick(){if(!S.playing)return;clearTimeout(timer);timer=setTimeout(()=>{if(S.frame<S.frames.length-1)S.frame++;else if(S.loop)S.frame=0;else{S.playing=false;$('playBtn').textContent='▶ Reproduzir';return}selectFrame(S.frame);tick()},1000/S.fps)}
function zoomAt(next,cx,cy){next=clamp(next,.5,64);let r=surface.getBoundingClientRect(),ox=(cx-r.left+surface.scrollLeft),oy=(cy-r.top+surface.scrollTop),old=S.zoom;S.zoom=next;renderCanvas();let factor=next/old;surface.scrollLeft=ox*factor-(cx-r.left);surface.scrollTop=oy*factor-(cy-r.top);$('zoomLabel').textContent=Number.isInteger(next)?next+'×':next.toFixed(1)+'×'}
function fit(){let r=surface.getBoundingClientRect(),pad=42;let z=Math.min((r.width-pad)/S.w,(r.height-pad)/S.h);z=clamp(Math.floor(z),1,64);zoomAt(z,r.width/2,r.height/2);surface.scrollLeft=0;surface.scrollTop=0}
function setTool(t){S.tool=t;document.querySelectorAll('.tool').forEach(b=>b.classList.toggle('active',b.dataset.tool===t));let q=tools.find(x=>x[0]===t);$('toolHint').textContent=q?`${q[2]} — ${q[3]}`:'';canvas.style.cursor=t==='zoom'?'zoom-in':t==='move'?'grab':'crosshair'}
function render(){document.body.classList.toggle('dark',S.dark);$('projectName').textContent=S.name;$('canvasSize').textContent=`${S.w} × ${S.h}`;$('gridBtn').textContent=S.grid?'Grade':'Grade oculta';$('selectionBtn').classList.toggle('active',S.tool==='select');$('zoomLabel').textContent=(Number.isInteger(S.zoom)?S.zoom:S.zoom.toFixed(1))+'×';$('opacity').value=Math.round((active()?.opacity||1)*100);$('opacityValue').textContent=$('opacity').value+'%';$('paletteLimit').value=String(S.paletteLimit||0);$('fps').value=String(S.fps);$('loop').checked=S.loop;$('symmetry').checked=S.symmetry;$('dither').checked=S.dither;$('onion').checked=S.onion;$('currentColor').style.background=S.color;$('previousColor').style.background=S.prev;renderCanvas();renderLayers();renderPalette();renderFrames();setTool(S.tool)}
function toast(t){let e=$('toast');e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1200)}
function newProject(){S.name=$('newName').value.trim()||'Meu desenho';S.w=clamp(+$('newW').value||32,1,256);S.h=clamp(+$('newH').value||32,1,256);S.bg=$('newBg').value;S.grid=$('newGrid').checked;S.zoom=16;S.frames=[mkFrame()];S.frame=0;S.activeLayer=S.frames[0].layers[1].id;S.history=[];S.future=[];S.selection=null;render();fit();save();toast('Projeto criado')}
function exportCanvas(format,scale,frame){let c=document.createElement('canvas');c.width=S.w*scale;c.height=S.h*scale;let x=c.getContext('2d');x.imageSmoothingEnabled=false;x.scale(scale,scale);drawScene(x,frame);let type=format==='jpg'?'image/jpeg':'image/png';if(format==='gif'){downloadGIF(scale);return}c.toBlob(b=>downloadBlob(b,`${safe(S.name)}.${format}`),type,.92)}
function safe(n){return(n||'pixel-studio').replace(/[^\w\-À-ÿ ]+/g,'').trim().replace(/\s+/g,'-').slice(0,60)||'pixel-studio'}
function downloadBlob(b,n){let a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function gifBytes(){toast('GIF será exportado em seguida')}
function downloadGIF(scale){if(S.frames.length>1){toast('GIF: use um editor GIF externo por enquanto');return}exportCanvas('png',scale,current())}
function initUI(){let tg=$('toolGrid');tg.innerHTML='';tools.forEach(t=>{let b=document.createElement('button');b.className='tool';b.dataset.tool=t[0];b.title=`${t[2]} · ${t[4]}`;b.innerHTML=`<b>${t[1]}</b> ${t[2]}<small>${t[4]}</small>`;b.onclick=()=>setTool(t[0]);tg.append(b)});let sr=$('sizeRow');sr.innerHTML='';[1,2,3,4,8].forEach(n=>{let b=document.createElement('button');b.className='size';b.textContent=n+' px';b.onclick=()=>{S.size=n;document.querySelectorAll('.size').forEach(x=>x.classList.toggle('active',x===b))};sr.append(b)});document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{$('newW').value=b.dataset.preset;$('newH').value=b.dataset.preset});}
let down=null,painting=false,spacePan=false,lastPinch=0;
function pointerDown(e){if(e.button!==undefined&&e.button!==0)return;if(S.space||e.shiftKey){spacePan=true;surface.classList.add('panning');down={sx:e.clientX,sy:e.clientY,sl:surface.scrollLeft,st:surface.scrollTop};return}let p=point(e);if(!inside(p.x,p.y))return;if(S.tool==='zoom'){zoomAt(S.zoom*1.5,e.clientX,e.clientY);return}if(S.tool==='select'){down={p};S.selection=null;renderSelection();return}if(S.tool==='move'&&S.selection){down={p,orig:{...S.selection},before:selectionData()};return}if(['line','rect','circle'].includes(S.tool)){down={p};return}commit();painting=true;apply(p,e);renderCanvas();save()}
function apply(p,e){if(S.tool==='pencil'||S.tool==='brush')paint(p.x,p.y);else if(S.tool==='eraser')paint(p.x,p.y,null);else if(S.tool==='fill')flood(p.x,p.y);else if(S.tool==='picker'){let l=active(),v=l?.pixels[idx(p.x,p.y)];if(v)setColor(v);addRecent(v||S.color);setTool('pencil')}else if(S.tool==='move'&&S.selection){} }
function pointerMove(e){let p=point(e);if(validPoint(p))$('coords').textContent=`x: ${p.x}, y: ${p.y}`;if(spacePan&&down){surface.scrollLeft=down.sl-(e.clientX-down.sx);surface.scrollTop=down.st-(e.clientY-down.sy);return}if(!down)return;if(S.tool==='select'){if(p){let a=down.p;S.selection={x:Math.min(a.x,p.x),y:Math.min(a.y,p.y),w:Math.abs(a.x-p.x)+1,h:Math.abs(a.y-p.y)+1};renderSelection()}return}if(S.tool==='move'&&S.selection){let dx=p.x-down.p.x,dy=p.y-down.p.y;if(dx||dy){let d=down.before,l=active(),nx=clamp(d.s.x+dx,0,S.w-d.s.w),ny=clamp(d.s.y+dy,0,S.h-d.s.h);for(let y=0;y<d.s.h;y++)for(let x=0;x<d.s.w;x++)l.pixels[idx(d.s.x+x,d.s.y+y)]=null;for(let y=0;y<d.s.h;y++)for(let x=0;x<d.s.w;x++)l.pixels[idx(nx+x,ny+y)]=d.pixels[y*d.s.w+x];S.selection={x:nx,y:ny,w:d.s.w,h:d.s.h};renderCanvas()}return}if(down.p&&['line','rect','circle'].includes(S.tool)){renderCanvas();let ctx=canvas.getContext('2d');ctx.save();ctx.globalAlpha=.6;ctx.strokeStyle=S.color;ctx.fillStyle=S.color;let a=down.p;line(a.x,a.y,p.x,p.y,()=>{});if(S.tool==='line')line(a.x,a.y,p.x,p.y,(x,y)=>ctx.fillRect(x,y,1,1));else{let x0=Math.min(a.x,p.x),x1=Math.max(a.x,p.x),y0=Math.min(a.y,p.y),y1=Math.max(a.y,p.y);if(S.tool==='rect')ctx.strokeRect(x0+.5,y0+.5,x1-x0,y1-y0);else ctx.strokeStyle=S.color,ctx.beginPath(),ctx.ellipse((x0+x1)/2,(y0+y1)/2,Math.max(.5,(x1-x0)/2),Math.max(.5,(y1-y0)/2),0,0,Math.PI*2),ctx.stroke()}ctx.restore()}if(painting){apply(p,e);renderCanvas()}}
function pointerUp(e){if(spacePan){spacePan=false;surface.classList.remove('panning');down=null;return}if(!down)return;if(['line','rect','circle'].includes(S.tool)){let p=point(e);if(validPoint(p)){commit();shape(S.tool,down.p,p);render();save()}}else if(S.tool==='select'){render()}else if(S.tool==='move'&&S.selection){render();save()}down=null;painting=false}
function wheel(e){e.preventDefault();let factor=e.deltaY<0?1.25:.8;zoomAt(S.zoom*factor,e.clientX,e.clientY)}
function bind(){
$('newBtn').onclick=()=>{let d=$('projectDialog');d.showModal()};$('saveBtn').onclick=()=>save(true);$('exportBtn').onclick=()=>{let d=$('exportDialog');d.showModal()};$('undoBtn').onclick=undo;$('redoBtn').onclick=redo;$('zoomIn').onclick=()=>zoomAt(S.zoom*1.25,surface.getBoundingClientRect().left+surface.clientWidth/2,surface.getBoundingClientRect().top+surface.clientHeight/2);$('zoomOut').onclick=()=>zoomAt(S.zoom*.8,surface.getBoundingClientRect().left+surface.clientWidth/2,surface.getBoundingClientRect().top+surface.clientHeight/2);$('fitBtn').onclick=fit;$('gridBtn').onclick=()=>{S.grid=!S.grid;render();save()};$('selectionBtn').onclick=()=>setTool('select');$('themeBtn').onclick=()=>{S.dark=!S.dark;render();save()};
$('colorPicker').oninput=e=>setColor(e.target.value);$('hexInput').onchange=e=>setColor(e.target.value);$('rgbInput').onchange=e=>{let a=e.target.value.split(',').map(Number);if(a.length===3&&a.every(n=>Number.isFinite(n)&&n>=0&&n<=255))setColor('#'+a.map(n=>Math.round(n).toString(16).padStart(2,'0')).join(''))};$('currentColor').onclick=()=>$('colorPicker').click();$('previousColor').onclick=()=>setColor(S.prev);$('swapColors').onclick=()=>{let x=S.color;S.color=S.prev;S.prev=x;setColor(S.color)};$('addColor').onclick=()=>{if(!S.palette.includes(S.color))S.palette.push(S.color);renderPalette();save()};$('removeColor').onclick=()=>{S.palette=S.palette.filter(c=>c!==S.color);renderPalette();save()};
$('mirrorH').onclick=()=>mirror(true);$('mirrorV').onclick=()=>mirror(false);$('symmetry').onchange=e=>{S.symmetry=e.target.checked;save()};$('dither').onchange=e=>{S.dither=e.target.checked;save()};$('onion').onchange=e=>{S.onion=e.target.checked;renderCanvas();save()};$('paletteLimit').onchange=e=>{S.paletteLimit=+e.target.value;save();toast(S.paletteLimit?`Limite: ${S.paletteLimit} cores`:'Paleta sem limite')};
$('addLayer').onclick=()=>{commit();let f=current(),l=mkLayer(`Camada ${f.layers.length+1}`);f.layers.push(l);S.activeLayer=l.id;render();save()};$('clearLayer').onclick=()=>{let l=active();if(!l||l.locked)return;commit();l.pixels=blank();render();save()};$('renameLayer').onclick=()=>{let l=active(),n=prompt('Nome da camada:',l?.name||'Camada');if(l&&n?.trim()){commit();l.name=n.trim();render();save()}};$('duplicateLayer').onclick=()=>{let l=active();if(!l)return;commit();let n={...l,id:uid(),name:l.name+' cópia',pixels:l.pixels.slice()};current().layers.splice(current().layers.indexOf(l)+1,0,n);S.activeLayer=n.id;render();save()};$('deleteLayer').onclick=()=>{let f=current();if(f.layers.length<=1)return;commit();let i=f.layers.findIndex(l=>l.id===S.activeLayer);f.layers.splice(i,1);S.activeLayer=f.layers[Math.max(0,i-1)].id;render();save()};$('layerUp').onclick=()=>layerMove(1);$('layerDown').onclick=()=>layerMove(-1);$('opacity').oninput=e=>{let l=active();if(l){l.opacity=+e.target.value/100;$('opacityValue').textContent=e.target.value+'%';renderCanvas();save()}};
$('copyBtn').onclick=()=>copy(false);$('cutBtn').onclick=()=>copy(true);$('pasteBtn').onclick=paste;$('duplicateSelection').onclick=()=>{let d=selectionData();if(!d)return;S.clipboard=d;paste()};$('deleteSelection').onclick=clearSel;
$('addFrame').onclick=()=>addFrame(true);$('duplicateFrame').onclick=()=>addFrame(true);$('deleteFrame').onclick=()=>deleteFrame();$('frameUp').onclick=()=>shiftFrame(-1);$('frameDown').onclick=()=>shiftFrame(1);$('prevFrame').onclick=()=>selectFrame(S.frame-1<0&&S.loop?S.frames.length-1:S.frame-1);$('nextFrame').onclick=()=>selectFrame(S.frame+1>=S.frames.length&&S.loop?0:S.frame+1);$('playBtn').onclick=play;$('fps').onchange=e=>{S.fps=+e.target.value;save()};$('loop').onchange=e=>{S.loop=e.target.checked;save()};
$('createProject').onclick=e=>{e.preventDefault();newProject();$('projectDialog').close()};$('doExport').onclick=e=>{e.preventDefault();exportCanvas($('exportFormat').value,+$('exportScale').value,current());$('exportDialog').close()};$('helpBtn').onclick=()=>{$('helpDialog').showModal();localStorage.setItem('pixel-studio-help','1')};$('closeHelp').onclick=()=>$('helpDialog').close();$('closeHelp2').onclick=()=>$('helpDialog').close();
canvas.addEventListener('pointerdown',pointerDown);canvas.addEventListener('pointermove',pointerMove);window.addEventListener('pointerup',pointerUp);surface.addEventListener('wheel',wheel,{passive:false});window.addEventListener('keydown',key);window.addEventListener('keyup',e=>{if(e.code==='Space')S.space=false});document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>$(b.dataset.open).classList.add('open'));document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).classList.remove('open'));window.addEventListener('resize',()=>renderSelection());
}
function mirror(horizontal){commit();for(const f of S.frames)for(const l of f.layers){let p=blank();for(let y=0;y<S.h;y++)for(let x=0;x<S.w;x++){let sx=horizontal?S.w-1-x:x,sy=horizontal?y:S.h-1-y;p[idx(x,y)]=l.pixels[idx(sx,sy)]}l.pixels=p}render();save()}
function layerMove(dir){let f=current(),i=f.layers.findIndex(l=>l.id===S.activeLayer),j=clamp(i+dir,0,f.layers.length-1);if(i===j)return;commit();[f.layers[i],f.layers[j]]=[f.layers[j],f.layers[i]];render();save()}
function key(e){let tag=document.activeElement?.tagName;if(['INPUT','SELECT','TEXTAREA'].includes(tag))return;if(e.code==='Space'){S.space=true;e.preventDefault();return}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();return}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();save(true);return}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='c'){e.preventDefault();copy(false);return}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='x'){e.preventDefault();copy(true);return}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='v'){e.preventDefault();paste();return}if(S.selection&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();moveSel(e.key==='ArrowLeft'?-1:e.key==='ArrowRight'?1:0,e.key==='ArrowUp'?-1:e.key==='ArrowDown'?1:0);return}let m={p:'pencil',b:'brush',e:'eraser',g:'fill',i:'picker',l:'line',r:'rect',c:'circle',s:'select',m:'move',z:'zoom'}[e.key.toLowerCase()];if(m)setTool(m);if(e.key==='+'||e.key==='=')zoomAt(S.zoom*1.25,innerWidth/2,innerHeight/2);if(e.key==='-')zoomAt(S.zoom*.8,innerWidth/2,innerHeight/2)}
load();initUI();bind();render();if(!localStorage.getItem('pixel-studio-help'))setTimeout(()=>$('helpDialog').showModal(),350);
})();